smtp:
  host: smtp.mailgun.org
  port: 25
  user: gunter@sandboxfe3907610f5c4d15bcf84655631ea2f9.mailgun.org
  password:
  from: gunter@guntercorp.com

database:
  dsn: stori:1q2w3e@tcp(mariadb_stori:3306)/storidb

txnprocessing:
  incomingdir: /app/stori-challenge/csv/incoming
  archivedir: /app/stori-challenge/csv/archive
  filenameregexp: \d\d\d\d\d\d\d\d_([a-zA-Z0-9]+)\.csv

schedule:
  seconds: 10