smtp:
  host: smtp.mailgun.org
  port: 25
  user: gunter@sandboxfe3907610f5c4d15bcf84655631ea2f9.mailgun.org
  password:
  from: gunter@guntercorp.com

database:
  dsn: stori:1q2w3e@tcp(localhost:3306)/storidb

txnprocessing:
  incomingdir: /Users/gunter/stori/incoming
  archivedir: /Users/gunter/stori/archive
  filenameregexp: \d\d\d\d\d\d\d\d_([a-zA-Z0-9]+)\.csv

schedule:
  seconds: 10
